- packages/experience/worlds.json
- packages/world/script/MoveScript.s.sol
- packages/world/src/Utils.sol
- packages/world/src/systems/BuildSystem.sol
- packages/world/src/systems/DropSystem.sol
- packages/world/src/systems/LoginSystem.sol
- packages/world/src/systems/MineSystem.sol
- packages/world/src/systems/OreSystem.sol
- packages/world/src/systems/PickupSystem.sol
- packages/world/src/systems/SpawnSystem.sol
- packages/world/src/systems/TerrainSystem.sol
- packages/world/src/systems/libraries/GravityLib.sol
- packages/world/src/systems/libraries/MoveLib.sol
- packages/world/src/systems/libraries/TerrainLib.sol
- packages/world/test/Terrain.t.sol
- packages/world/test/utils/TestUtils.sol
- packages/world/test/utils/encodeChunk.sol
- packages/world/worlds.json
Was previously removed as we were unsure how we were doing terrain
> Add back checks for terrain and creating entities

- packages/experience/worlds.json
- packages/world/script/TestScript.s.sol
- packages/world/test/BiomesTest.sol
- packages/world/test/Chip.t.sol
- packages/world/test/Equip.t.sol
- packages/world/test/ForceField.t.sol
- packages/world/test/Gravity.t.sol
- packages/world/test/Mine.t.sol
- packages/world/test/Spawn.t.sol
- packages/world/test/utils/TestUtils.sol
- packages/world/worlds.json
I noticed there were some outdated utils due to code being duplicated and not updated, so created this lib that allows us to call utils that use root methods directly
> Support calling test utils as the world

- packages/experience/worlds.json
- packages/world/src/systems/libraries/TerrainLib.sol
- packages/world/test/Terrain.t.sol
- packages/world/worlds.json
pulled in changes from https://github.com/tenetxyz/biomes-contracts/pull/68 for main
> add terrain system fixes

- packages/world/src/ObjectTypes.sol
corresponding client PR: https://github.com/tenetxyz/biomes-client/pull/498
> add more blocks for new map

- packages/experience/worlds.json
- packages/world/src/ObjectTypeLib.sol
- packages/world/src/systems/MachineSystem.sol
- packages/world/src/systems/MineSystem.sol
- packages/world/worlds.json
Fixes https://github.com/tenetxyz/biomes-contracts/issues/85
- Tests for powering will come up with farming
> Add machine check before updating energy on mine

- packages/experience/worlds.json
- packages/world/src/systems/SpawnSystem.sol
- packages/world/worlds.json
> Fix player existence check in spawn system

- packages/world/src/ObjectTypeLib.sol
> Disallow mining lava

- packages/world/src/systems/libraries/TerrainLib.sol
- packages/world/test/BiomesTest.sol
- packages/world/test/Terrain.t.sol
- packages/world/test/utils/encodeChunk.sol
- packages/world/worlds.json
corresponding client PR: https://github.com/tenetxyz/biomes-client/pull/532
> feat: add biomes to terrain

- packages/world/src/systems/libraries/TerrainLib.sol
- packages/world/test/BiomesTest.sol
- packages/world/test/Terrain.t.sol
- packages/world/test/utils/encodeChunk.sol
corresponding client PR: https://github.com/tenetxyz/biomes-client/pull/533
> feat: add surface indicator byte

- packages/world/IWorld.abi.json
- packages/world/IWorld.abi.json.d.ts
- packages/world/src/Types.sol
- packages/world/src/systems/helper/ReadSystem.sol
- packages/world/worlds.json
- Needed for clients to know if a force field fragment is stale
> add machine data to getter

- .github/workflows/publish-preview.yml
- package.json
see https://github.com/stackblitz-labs/pkg.pr.new
> publish package preview

- PROGRAMS.md
- packages/programs/src/programs/ForceFieldProgram.sol
- packages/world/src/ProgramInterfaces.sol
- packages/world/src/codegen/world/IBuildSystem.sol
- packages/world/src/codegen/world/IMineSystem.sol
- packages/world/src/codegen/world/IProgramSystem.sol
- packages/world/src/codegen/world/ITransferSystem.sol
- packages/world/src/systems/BuildSystem.sol
- packages/world/src/systems/MineSystem.sol
- packages/world/src/systems/ProgramSystem.sol
- packages/world/src/systems/TransferSystem.sol
> Remove payable from all hooks

- packages/world/src/EntityId.sol
- packages/world/src/Vec3.sol
- packages/world/src/systems/ForceFieldSystem.sol
- packages/world/src/systems/ProgramSystem.sol
- packages/world/src/utils/ForceFieldUtils.sol
- packages/world/test/Build.t.sol
- packages/world/test/ForceField.t.sol
> Add fragment adjacency check

- packages/programs/src/programs/DefaultProgram.sol
- packages/programs/src/programs/ForceFieldProgram.sol
- packages/world/worlds.json
- Add fuel hook to force field program
- Add fallback hook for all default programs
> Add fuel hook to force field program & fallback hook

- packages/world/src/Constants.sol
- packages/world/src/EntityId.sol
- packages/world/src/systems/BedSystem.sol
- packages/world/src/systems/BuildSystem.sol
- packages/world/src/systems/MineSystem.sol
- packages/world/src/systems/MoveSystem.sol
- packages/world/src/systems/admin/AdminSystem.sol
- packages/world/src/systems/libraries/MoveLib.sol
- packages/world/test/ForceField.t.sol
- packages/world/test/Gravity.t.sol
- packages/world/test/Move.t.sol
- Refactored move lib
- Fixed off by one error when computing path result
- Fixed energy calculation when landing on water
- Don't decrease energy in falls (below threshold)
> Fix landing on water

- packages/world/mud.config.ts
- packages/world/script/initObjects.sol
- packages/world/src/ObjectType.sol
- packages/world/src/systems/BuildSystem.sol
- packages/world/src/systems/MineSystem.sol
- packages/world/src/systems/NatureSystem.sol
- packages/world/test/Farming.t.sol
- packages/world/test/Tree.t.sol
- packages/world/ts/objects.ts
- packages/world/ts/scripts/genInitObjectsSol.ts
- packages/world/ts/scripts/genObjectTypeSol.ts
move seed energy to a getter instead of an object, as it makes more sense conceptually (the seed itself doesn't have energy, only the crop/tree does)
> Seed energy getter

- packages/programs/src/WhitelistSystem.sol
- packages/programs/src/programs/DefaultProgram.sol
Trying to figure out a way to check the forcefield's energy... will first test how much gas increases if we use non-root table reads in utils
> Move owner functions to WhitelistSystem

- packages/world/ts/entityid.ts
you can pass a mutable array to a readonly param but not the other way around
> change utils to accept readonly vec3

- packages/world/src/OreLib.sol
> fix: biome ids

- packages/dustkit/contracts/IDisplay.sol
- packages/programs/mud.config.ts
- packages/programs/package.json
- packages/programs/remappings.txt
- packages/programs/src/DefaultProgramSystem.sol
- packages/programs/src/codegen/index.sol
- packages/programs/src/codegen/systems/DefaultProgramSystemLib.sol
- packages/programs/src/codegen/tables/TextSignContent.sol
- packages/programs/src/programs/TextSignProgram.sol
- pnpm-lock.yaml
- Move interface to dustkit
- Store text directly in TextSignContent table
> chore: text sign content

- packages/world/src/systems/MineSystem.sol
- packages/world/test/Mine.t.sol
- Only check that block has at least one passthrough block as neighbor
- Add tests
> Add reachability tests, and make it less strict

- packages/world/src/types/ObjectType.sol
- packages/world/ts/scripts/genObjectTypeSol.ts
> Allow planting saplings on moss
